import Head from 'next/head'
import Header from '../Components/Home/Header/Header';
// import Image from 'next/image'
import styles from '../styles/Home.module.css';
// import und_con from '../public/images/under_construction.JPG'
// import nazifa from '../'



export default function Home() {

  const {container,main}=styles

  return (
    <div className={container}>
      <Head>
        <title>Nazifa Tamanna Islam</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        {/* <link rel="icon" href="1626375126335.jfif" /> */}
        <link rel="icon" href="/nazifa_1.png"/>
      </Head>

      <main className={`${main}`}>
        
        {/* <img src="https://thumbs.dreamstime.com/b/under-construction-heart-heart-as-under-construction-sign-113817361.jpg" alt="" width="50%"/> */}
        {/* <img src="./images/nazifa.png" alt="nazifa" width="50%"/> */}
        {/* <img src={require('./images/under_construction.JPG')} /> */}

        <div className="container">
          <div className="row  "> 
            <div className="col-md-6">
              <img className="img-fluid  rounded-circle" src="./images/nazifa.png" alt="nazifa" width="50%"/>
            </div>
            <div className="col-md-6 under_cons">
                <span className="one">The</span> <span className="two">Site</span> <span className="three">is</span> <span className="four">Under</span> <span className="five"> Construction</span>
            </div>
          </div>
        </div>
      </main>



     

      <Header/>
          </div>
  )
}
