import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Nazifa Tamanna Islam</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
        <link rel="icon" href="1626375126335.jfif" />
      </Head>

      <main className={styles.main}>
        <h3>WelCome, The site is under Construction ↓↓ ↑↑</h3>
        <img src="https://thumbs.dreamstime.com/b/under-construction-heart-heart-as-under-construction-sign-113817361.jpg" alt="" width="50%"/>
      </main>

      
    </div>
  )
}
